version: '3'
services:
  tetris-client-dev:
    image: node:10
    container_name: tetris-client-dev
    volumes:
      - ./client:/home/node/public/
    environment:
      - REACT_APP_TETRIS_APP_PORT=3005
      - REACT_APP_DOMAIN=0.0.0.0
      - REACT_APP_TETRIS_API_PORT=3006
      - REACT_APP_NODE_ENV=devlopment
    working_dir: /home/node/public
    command: "bash -c 'npm install; npm run build; npm run start'"
    ports:
      - 3005:3005
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user42
      POSTGRES_PASSWORD: example
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    restart: always

  db_admin:
    image: adminer
    container_name: db_admin
    restart: always
    depends_on:
      - db
    ports:
      - 3004:8080
    links:
      - db

  tetris-api-dev:
    image: node:10
    container_name: tetris-api-dev
    volumes:
      - ./server:/home/node/app/api
    environment:
      - MAIN_PORT=3006
      - DOMAIN=0.0.0.0
      - PG_HOST=db
      - POSTGRES_USER=user42
      - POSTGRES_PASSWORD=example
      - POSTGRES_PORT=5432
    working_dir: /home/node/app/api
    command: "bash -c 'npm install; npm run server:dev'"
    ports:
      - 3006:3006
    restart: always
    depends_on:
      - db_admin
      - db
